<?php

function getNewPublicUrl($db)
{
    $statement = $db->prepare("SELECT COUNT(*) AS COUNT FROM snippets WHERE url_public=:candidate");
    for ($i = 0; $i < 100; $i++) {
        $candidate = getPublicUrl();
        if (!urlExists($statement, $candidate)) {
            return $candidate;
        }
    }
    throw new Exception("Could not find new public url");
}

function getPublicUrl()
{
    $keys = array_rand(NAMES, 4);
    shuffle($keys);
    $value = "";
    foreach ($keys as $key) {
        $value .= NAMES[$key];
    }
    return $value;
}

function getNewPrivateUrl($db)
{
    $statement = $db->prepare("SELECT COUNT(*) AS COUNT FROM snippets WHERE url_private=:candidate");
    for ($i = 0; $i < 100; $i++) {
        $candidate = getPrivateUrl();
        if (!urlExists($statement, $candidate)) {
            return $candidate;
        }
        return $candidate;
    }
    throw new Exception("Could not find new private url");
}

function getPrivateUrl()
{
    $bytes = random_bytes(16);
    return bin2hex($bytes);
}

function urlExists($statement, $candidate)
{
    $statement->bindValue(':candidate', $candidate);
    $result = $statement->execute();
    if ($result !== false) {
        $row = $result->fetchArray(SQLITE3_ASSOC);
        $result->finalize();
        if ($row !== false) {
            return $row['COUNT'] === 1;
        }
    }
    throw new Exception("Could not check if url exists");
}

define("NAMES", ["Anarchy",
    "AndeanSling",
    "Arambai",
    "Arbalest",
    "Archer",
    "ArcheryRange",
    "Architecture",
    "Arquebus",
    "Arrowslits",
    "Arson",
    "Artillery",
    "Atheism",
    "Atlatl",
    "Atonement",
    "BallistaElephant",
    "Ballistics",
    "Banking",
    "Barracks",
    "BatteringRam",
    "BattleElephant",
    "BeardedAxe",
    "Berserk",
    "Berserkergang",
    "Blacksmith",
    "BlastFurnace",
    "BlockPrinting",
    "Bloodlines",
    "BodkinArrow",
    "BoilingOil",
    "BombardCannon",
    "BombardTower",
    "BowSaw",
    "Boyar",
    "Bracer",
    "Camel",
    "CamelArcher",
    "CannonGalleon",
    "CappedRam",
    "Caravan",
    "Caravel",
    "Careening",
    "Carrack",
    "Cartography",
    "Castle",
    "CastleAge",
    "Cataphract",
    "Cavalier",
    "CavalryArcher",
    "ChainBardingArmor",
    "ChainMailArmor",
    "Champion",
    "Chatras",
    "Chemistry",
    "Chieftains",
    "Chivalry",
    "ChuKoNu",
    "Coinage",
    "Condottiero",
    "Conquistador",
    "Conscription",
    "Couriers",
    "Crenellations",
    "CropRotation",
    "Crossbowman",
    "DemolitionRaft",
    "DemolitionShip",
    "Dock",
    "DoubleBitAxe",
    "DoubleCrossbow",
    "Drill",
    "Druzhina",
    "DryDock",
    "EagleScout",
    "EagleWarrior",
    "ElDorado",
    "ElephantArcher",
    "EliteArambai",
    "EliteBallistaElephant",
    "EliteBattleElephant",
    "EliteBerserk",
    "EliteBoyar",
    "EliteCamelArcher",
    "EliteCannonGalleon",
    "EliteCaravel",
    "EliteCataphract",
    "EliteChuKoNu",
    "EliteConquistador",
    "EliteEagleWarrior",
    "EliteElephantArcher",
    "EliteGbeto",
    "EliteGenitour",
    "EliteGenoeseCrossbowman",
    "EliteHuskarl",
    "EliteJaguarWarrior",
    "EliteJanissary",
    "EliteKamayuk",
    "EliteKarambitWarrior",
    "EliteLongboat",
    "EliteLongbowman",
    "EliteMagyarHuszar",
    "EliteMameluke",
    "EliteMangudai",
    "EliteOrganGun",
    "ElitePlumedArcher",
    "EliteRattanArcher",
    "EliteSamurai",
    "EliteShotelWarrior",
    "EliteSkirmisher",
    "EliteTarkan",
    "EliteTeutonicKnight",
    "EliteThrowingAxeman",
    "EliteTurtleShip",
    "EliteWarElephant",
    "EliteWarWagon",
    "EliteWoadRaider",
    "Faith",
    "Farimba",
    "Farm",
    "FastFireShip",
    "Feitoria",
    "Fervor",
    "FeudalAge",
    "FireGalley",
    "FireShip",
    "FishingShip",
    "FishTrap",
    "Fletching",
    "ForcedLevy",
    "Forging",
    "FortifiedWall",
    "FurorCeltica",
    "Galleon",
    "Galley",
    "GarlandWars",
    "Gate",
    "Gbeto",
    "Genitour",
    "GenoeseCrossbowman",
    "Gillnets",
    "GoldMining",
    "GoldShaftMining",
    "GreatWall",
    "GreekFire",
    "GuardTower",
    "Guilds",
    "Halberdier",
    "HandCannoneer",
    "HandCart",
    "HeatedShot",
    "HeavyCamel",
    "HeavyCavArcher",
    "HeavyDemoShip",
    "HeavyPlow",
    "HeavyScorpion",
    "HerbalMedicine",
    "Heresy",
    "Hoardings",
    "HorseCollar",
    "House",
    "Howdah",
    "Husbandry",
    "Huskarl",
    "Hussar",
    "Illumination",
    "ImperialAge",
    "ImperialCamel",
    "ImperialSkirmisher",
    "Inquisition",
    "IronCasting",
    "Ironclad",
    "JaguarWarrior",
    "Janissary",
    "Kamayuk",
    "KarambitWarrior",
    "Kasbah",
    "Kataparuto",
    "Keep",
    "Knight",
    "LeatherArcherArmor",
    "LightCavalry",
    "Logistica",
    "Longboat",
    "Longbowman",
    "LongSwordsman",
    "Loom",
    "LumberCamp",
    "Madrasah",
    "MaghrabiCamels",
    "MagyarHuszar",
    "Mahouts",
    "Mameluke",
    "ManatArms",
    "Mangonel",
    "Mangudai",
    "ManipurCavalry",
    "Marauders",
    "Market",
    "Masonry",
    "Mercenaries",
    "Militia",
    "Mill",
    "MiningCamp",
    "Missionary",
    "Monastery",
    "Monk",
    "MurderHoles",
    "Nomads",
    "ObsidianArrows",
    "Onager",
    "OrganGun",
    "Orthodoxy",
    "Outpost",
    "PaddedArcherArmor",
    "Paladin",
    "PalisadeGate",
    "PalisadeWall",
    "Panokseon",
    "PaperMoney",
    "ParthianTactics",
    "Pavise",
    "Perfusion",
    "Petard",
    "Pikeman",
    "PlateBardingArmor",
    "PlateMailArmor",
    "PlumedArcher",
    "RattanArcher",
    "RecurveBow",
    "Redemption",
    "RingArcherArmor",
    "Rocketry",
    "RoyalHeirs",
    "Samurai",
    "Sanctity",
    "Sappers",
    "ScaleBardingArmor",
    "ScaleMailArmor",
    "Scorpion",
    "ScoutCavalry",
    "Shatagni",
    "Shinkichon",
    "Shipwright",
    "ShotelWarrior",
    "SiegeEngineers",
    "SiegeOnager",
    "SiegeRam",
    "SiegeWorkshop",
    "SilkRoad",
    "Sipahi",
    "Skirmisher",
    "Slinger",
    "Spearman",
    "Spies",
    "Squires",
    "Stable",
    "StoneMining",
    "StoneShaftMining",
    "StoneWall",
    "Stronghold",
    "Sultans",
    "Supremacy",
    "Tarkan",
    "TeutonicKnight",
    "Thalassocracy",
    "Theocracy",
    "ThrowingAxeman",
    "ThumbRing",
    "Tigui",
    "TorsionEngines",
    "TownCenter",
    "TownPatrol",
    "TownWatch",
    "Tracking",
    "TradeCart",
    "TradeCog",
    "TransportShip",
    "TreadmillCrane",
    "Treason",
    "Trebuchet",
    "TurtleShip",
    "TuskSwords",
    "TwoHandedSwordsman",
    "TwoManSaw",
    "University",
    "Villager",
    "WarElephant",
    "WarGalley",
    "WarWagon",
    "Warwolf",
    "WatchTower",
    "Wheelbarrow",
    "WoadRaider",
    "Wonder",
    "Yasama",
    "Yeomen",
    "Zealotry"]);